import {StyleSheet} from 'react-native';
import {
  COLOR_GRAY_BACKGROUND,
  COLOR_LIGHT_GRAY,
  COLOR_PRIMARY,
  COLOR_PRIMARY_DARK,
  COLOR_SECONDARY,
  COLOR_WHITE,
} from '../../../constants/theme';

export default StyleSheet.create({
  homeTopContainer: {
    padding: 20,
  },
  text: {
    color: COLOR_PRIMARY_DARK,
    fontFamily: 'Helvetica',
    fontStyle: 'normal',
    fontWeight: '700',
  },
  greetingText: {
    fontSize: 20,
    marginTop: 28,
  },
  welcomeText: {
    fontSize: 30,
    marginBottom: 40,
  },
  scrollView: {
    display: 'flex',
    backgroundColor: COLOR_SECONDARY,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  noDevicesImage: {
    marginBottom: 22,
    marginTop: 100,
  },
  noDevicesText: {
    color: COLOR_WHITE,
    textAlign: 'center',
    fontFamily: 'Helvetica',
    fontSize: 20,
    fontWeight: '700',
    maxWidth: 215,
  },
  homeButtonsContainer: {
    height: 52,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  addButtonContainer: {
    padding: 5,
    backgroundColor: COLOR_WHITE,
    borderRadius: 100,
    marginTop: -52,
  },
  modal: {
    backgroundColor: COLOR_WHITE,
    marginHorizontal: 16,
    borderRadius: 15,
  },
  modalContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  addDeviceContainer: {
    gap: 32,
    alignSelf: 'stretch',
  },
  modalText: {
    fontFamily: 'Helvetica',
    fontWeight: '700',
  },
  modalTitle: {
    color: COLOR_PRIMARY_DARK,
    fontSize: 20,
    marginTop: 32,
  },
  activityIndicator: {
    marginTop: 45,
    marginBottom: 20,
  },
  modalSubtitle: {
    color: COLOR_SECONDARY,
    fontSize: 16,
  },
  modalCancelButton: {
    width: '100%',
    paddingVertical: 16,
    borderTopWidth: 0.5,
    borderStyle: 'solid',
    borderTopColor: COLOR_LIGHT_GRAY,
    marginTop: 50,
    display: 'flex',
    alignItems: 'center',
  },
  modalErrorImage: {
    marginTop: 36,
  },
  notFoundText: {
    color: COLOR_PRIMARY_DARK,
    fontSize: 16,
    fontWeight: '400',
    marginVertical: 16,
  },
  retryButton: {
    width: 250,
    paddingVertical: 10,
    borderRadius: 37,
    borderWidth: 1,
    borderColor: COLOR_PRIMARY,
    borderStyle: 'solid',
    display: 'flex',
    alignItems: 'center',
  },
  modalButtonText: {
    color: COLOR_PRIMARY,
    fontSize: 16,
  },
  deviceContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'stretch',
    borderRadius: 15,
    backgroundColor: COLOR_GRAY_BACKGROUND,
    marginHorizontal: 16,
    marginTop: 32,
    paddingHorizontal: 10,
    paddingVertical: 16,
  },
  deviceName: {
    color: COLOR_PRIMARY_DARK,
    fontSize: 14,
  },
  addDeviceButton: {
    display: 'flex',
    padding: 10,
    width: 95,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 37,
    backgroundColor: COLOR_PRIMARY,
  },
  addButtonText: {
    color: COLOR_WHITE,
    fontSize: 16,
  },
  nameInputContainer: {
    alignSelf: 'stretch',
    display: 'flex',
    gap: 8,
    marginHorizontal: 16,
  },
  input: {
    backgroundColor: COLOR_GRAY_BACKGROUND,
    paddingVertical: 16,
    paddingHorizontal: 10,
    borderRadius: 15,
    borderWidth: 0.5,
    borderStyle: 'solid',
    borderColor: COLOR_LIGHT_GRAY,
  },
  inputText: {
    color: COLOR_PRIMARY_DARK,
    fontSize: 16,
    fontWeight: '400',
  },
  distanceInput: {
    paddingHorizontal: 20,
    color: COLOR_PRIMARY_DARK,
    fontSize: 16,
    textAlign: 'center',
  },
  buttonsContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    borderTopWidth: 0.5,
    borderStyle: 'solid',
    borderTopColor: COLOR_LIGHT_GRAY,
  },
  modalButton: {
    flexGrow: 1,
    display: 'flex',
    alignItems: 'center',
    paddingVertical: 16,
  },
  modalRightButton: {
    borderLeftWidth: 0.5,
    borderStyle: 'solid',
    borderLeftColor: COLOR_LIGHT_GRAY,
  },
  distanceContainer: {
    alignSelf: 'stretch',
    display: 'flex',
    gap: 16,
    marginHorizontal: 16,
  },
  distanceControllerContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 24,
  },
  distanceButton: {
    padding: 10,
  },
});
